### ISSUE TITLE
Optional parameters/Object params

### ISSUE THREAD

**Issue by elmeerr** [andy-shea/redux-action-creator#4]
Hi Andy,

Congrats for the nice library.

I was wondering....how about creating the payload also based on object properties? 
Why?
If I'm not mistaken, right now we "can't" use optional parameters, if the parameter is optional, we need to give it's value when we call the action, otherwise could not match the function signature e.g:

`actionCreator('TYPE', 'optional params', 'required param')` 

is this case if we call the action like `action(value){}` the payload will be payload: `{optionalParam: value}` when it should be payload: `{requiredParam: value}`. Ok, we can change the order of the parameters and work this around but this is a thing that I think that can be improved by using Object params.

to achieve that, instead of adding a list of parameters, change this list into a Object param so that we will be able to call function like this `function({requiredParam: value}) ` and the payload will be `payload: {requiredParam: value}` and if we need the two params, just call `function({optionalParam: true, requiredParam: value})`

it will be something like

```
export function actionCreator(type, ...params) {
  return (argObj) => {
    return params.reduce((action, param, index) => {
      action.payload[param] = argObj[param];
      return action;
    }, {type, payload: {}});
  };
}
```

does not need to be a replacement, could perfectly be an extra option (then you avoid breaking changes)

I hope that's make sense to you

Regards,

**Comment by andy-shea** [comment]
If you want an action creator that accepts a payload object instead of individual payload properties you're probably better of defining the action creator yourself.  It would be as simple as:

```
payload => ({type: 'MY_ACTION_TYPE', ...payload})
```

This library is all about reducing boilerplate without introducing "magic" but there isn't much boilerplate to reduce with the most simple of action creators.  A "helper" here wouldn't be much more than:

```
function actionCreatorViaPayload(type) {
  return payload => ({type, ...payload});
}
```

In saying that, what I do like about passing in a payload object rather than individual parameters (besides the ability to support optional parameters more easily) is that it makes calling synchronous action creators more consistent with asynchronous action creators (which accept a payload object instead of individual parameters).

I'll think about this more, let me know your thoughts.

**Comment by elmeerr** [comment]
Actually for me, creating action creators it's nice (and give ou more control over how do you want to pass your payload) but the team I'm working choose you library to work with: no problem for me, really reduces the boilerplates and it is simple to use.

I just thought about this because I have this in .NET and I think it's a nice feature because makes code more readable for any developer in the team. As you like the approach (for more reasons than supporting optional parameters) I think you should consider changing the actual behavior or adding this option (I would choose the later as it's a breaking change). It will be a nice feature for the library.

ps.: it is just a suggestion, the library is already nice the way it is.
